version: 2
updates:
  # Check for updates in Python dependencies
  - package-ecosystem: "pip"
    directory: "/" # root directory where your Django requirements.txt or Pipfile is located
    schedule:
      interval: "weekly" # Check for updates weekly; options: daily, weekly, monthly
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 10
