name: Django CI/CD Workflow

on:
  push:
    branches:
      - minor_improvements
  pull_request:
    branches:
      - minor_improvements

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      # Use a service for the SQLite database (though Django will use the file-based SQLite)
      db:
        image: sqlite

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python 3.12
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        pip install -r requirements.txt

    # Step 4: Run Django migrations
    - name: Run migrations
      run: |
        source env/bin/activate
        python manage.py makemigrations
        python manage.py migrate

    # Step 5: Run tests
    - name: Run Django tests
      run: |
        source env/bin/activate
        python manage.py test

  docker-build:
    needs: build
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Build the Docker image
    - name: Build Docker image
      run: docker build -t calorie-counter-app .
